### ISSUE TITLE
Provide weights?

### ISSUE THREAD

**Issue by shreyaskamathkm** [DeepInsight-PCALab/MixNet#1]
Hi,
I am trying to access the weights provided by you on baidu. However, due to the lack of access to baidu I am unable to download it. Could you please provide it under different service? 

Thank you,
Best regards,
Shreyas Kamath

**Comment by whai362** [comment]
We upload weights on onedrive. You can find them at readme.

**Comment by shreyaskamathkm** [comment]
Thank you so much. The one drive links are not on the main page, so was confused.
